// File generated by FlutterFire CLI.
// Using real values from Firebase Console — lowcodeapp-1a7eb

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYr7YwA01eRQ2PjTF2gE2n4s4JkGjS7k',
    appId: '1:179239323540:web:02d6a5f984b6d4652ab181',
    messagingSenderId: '179239323540',
    projectId: 'lowcodeapp-1a7eb',
    authDomain: 'lowcodeapp-1a7eb.firebaseapp.com',
    storageBucket: 'lowcodeapp-1a7eb.firebasestorage.app',
    measurementId: 'G-2RQJYNX9RP',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  // Replace with values from your google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYr7YwA01eRQ2PjTF2gE2n4s4JkGjS7k',
    appId: '1:179239323540:android:02d6a5f984b6d4652ab181',
    messagingSenderId: '179239323540',
    projectId: 'lowcodeapp-1a7eb',
    storageBucket: 'lowcodeapp-1a7eb.firebasestorage.app',
  );

  // ── iOS ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYr7YwA01eRQ2PjTF2gE2n4s4JkGjS7k',
    appId: '1:179239323540:ios:02d6a5f984b6d4652ab181',
    messagingSenderId: '179239323540',
    projectId: 'lowcodeapp-1a7eb',
    storageBucket: 'lowcodeapp-1a7eb.firebasestorage.app',
    iosBundleId: 'com.gayathri.low_code_app',
  );

  // ── macOS ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYr7YwA01eRQ2PjTF2gE2n4s4JkGjS7k',
    appId: '1:179239323540:ios:02d6a5f984b6d4652ab181',
    messagingSenderId: '179239323540',
    projectId: 'lowcodeapp-1a7eb',
    storageBucket: 'lowcodeapp-1a7eb.firebasestorage.app',
    iosBundleId: 'com.gayathri.low_code_app',
  );
}
